name: Deploy Site

on:
  push:
    branches: [ master ]

jobs:
  site:
    runs-on: ubuntu-latest
    steps:
      - run: 'git config --global url."https://github.com/".insteadOf git@github.com:'
      - run: 'git config --global url."https://".insteadOf git://'

      - uses: actions/checkout@v2

      - uses: erlef/setup-elixir@v1
        with:
          otp-version: '23.2.5'
          elixir-version: '1.11.3'

      - name: Restore Cache
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
            _site
          key: mix-${{ hashFiles('mix.lock') }}

      - run: MIX_ENV=staging mix deps.get

      - run: MIX_ENV=staging mix still.compile

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
